CREATE TABLE IF NOT EXISTS `usuarios` (
    `id_User` INT NOT NULL AUTO_INCREMENT,
    `user` VARCHAR(100) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `ativo` BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY(`id_User`)
);